### ISSUE TITLE
As a user, I want to view on a map the correlation between a single Employment category and single Agricultural commodity, so that I can make a conclusion.

### ISSUE THREAD

**Issue by bmcelhaney** [swinkler149/901K-Sandbox#2] opened 2015-03-10 21:25 UTC

**Comment by eahollin** [comment] 2015-03-17 15:14
This is a dupe of AD002, right?  should this one be deleted since it has no number assigned?

**Comment by bmcelhaney** [comment] 2015-03-19 14:23
I believe it is a dupe.  Should we remove?

**Comment by eahollin** [comment] 2015-03-19 21:47
Yes

**Comment by eahollin** [comment] 2015-03-26 19:40
The only thing I can see how to do is "Close".  don't see a delete button... :(

**Closed as completed by eahollin** 2015-03-26 19:40 UTC
Labels: Story
